name: chaos
dependencies:
  # Supported Python version (conda is language-agnostic)
  - python=3.8
  # Data model:
  - pandas=1.3.4
  # Feature Engineering etc.:
  - scikit-learn=1.0.1
  # Graph library (used by grapresso):
  - networkx=2.5.1
  # Plotting:
  - matplotlib=3.4.3
  # Possible CLI capabilities in the future:
  - click=8.0.3
  # Progress bar:
  - tqdm=4.50.2
  # For projection of embeddings:
  - tensorflow=2.6.0
  # Processing metadata:
  - beautifulsoup4=4.9.1
  - markdown=3.3.2
  # ------------------------------------
  # From conda-forge (community-managed):
  - conda-forge::jupyterlab=3.2.0
  # NLP
  - conda-forge::spacy=2.3.7
  - conda-forge::spacy-model-en_core_web_md=2.3.1
  # Hybrid RS latent factor model:
  - conda-forge::lightfm=1.15
  # Visualizations:
  - conda-forge::altair=4.1.0
  # Hyperparameter Tuning:
  - conda-forge::optuna=2.10.0
  # GraphQL for GitHub example:
  - conda-forge::gql=2.0.0
  # Development dependencies:
  # ------------------------
  # Documentation:
  - sphinx
  # We use conda as a package manager, but pip for 3rd party packages that are better maintained in the PyPI.
  - pip
  - pip:
      - pytest>=5.4.3,<6.0.0
      # View visualizations by Altair (see altair above) in-browser:
      - altair_viewer>=0.3.0,<1.0.0
      # Meta Graph library (uses networkx above).
      # TODO(kdevo): Currently, the dev branch is embedded as a submodule
#      - grapresso<=1.0.0
