version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '[%(levelname)s] %(asctime)-s - %(name)s - %(message)s'
    datefmt: '%H:%M'
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout
root:
  level: INFO
  handlers: [ console ]